/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author delri
 */
import Model.Bean.ProducaoMelado;
import Model.Bean.ProducaoRapadura;
import Model.DAO.MeladoDAO;
import Model.DAO.RapaduraDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class ProducaoRapaduraMeladoView extends javax.swing.JFrame {

    /**
     * Creates new form ProducaoRapaduraMeladoView
     */
    public ProducaoRapaduraMeladoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Abas = new javax.swing.JTabbedPane();
        painelMelado = new javax.swing.JPanel();
        lblLoteMelado = new javax.swing.JLabel();
        txtLoteMelado = new javax.swing.JTextField();
        lblPesoTotalMelado = new javax.swing.JLabel();
        txtPesoTotalMelado = new javax.swing.JTextField();
        txtQtdCaldoMelado = new javax.swing.JTextField();
        lblQtdCaldoMelado = new javax.swing.JLabel();
        lblDtProdMelado = new javax.swing.JLabel();
        ftxtDtProdMelado = new javax.swing.JFormattedTextField();
        lblRendimentoMelado = new javax.swing.JLabel();
        txtRendimentoMelado = new javax.swing.JTextField();
        txtQtdMelado = new javax.swing.JTextField();
        lblQtdMelado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblAddMelado = new javax.swing.JLabel();
        lblPesoMelado = new javax.swing.JLabel();
        txtPesoMelado = new javax.swing.JTextField();
        btnAddMelado = new javax.swing.JButton();
        btnSalvarMelado = new javax.swing.JButton();
        btnMeladoVoltar = new javax.swing.JButton();
        btnRemoverMelado = new javax.swing.JButton();
        txtLabelEngarrafamento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMelado = new javax.swing.JTable();
        btnAtualizarMelado = new javax.swing.JButton();
        btnExcluirMelado = new javax.swing.JButton();
        painelRapadura = new javax.swing.JPanel();
        btnRapaduraVoltar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblAddRapadura = new javax.swing.JLabel();
        btnAddRapadura = new javax.swing.JButton();
        lblPesoRapadura = new javax.swing.JLabel();
        txtPesoRapadura = new javax.swing.JTextField();
        lblLoteRapadura = new javax.swing.JLabel();
        txtLoteRapadura = new javax.swing.JTextField();
        lblQtdCaldoRapadura = new javax.swing.JLabel();
        txtQtdCaldoRapadura = new javax.swing.JTextField();
        lblDtProdRapadura = new javax.swing.JLabel();
        ftxtDtProdRapadura = new javax.swing.JFormattedTextField();
        lblQtdRapadura = new javax.swing.JLabel();
        txtQtdRapadura = new javax.swing.JTextField();
        lblPesoTotalRapadura = new javax.swing.JLabel();
        txtPesoTotalRapadura = new javax.swing.JTextField();
        lblRendimentoRapadura = new javax.swing.JLabel();
        txtRendimentoRapadura = new javax.swing.JTextField();
        btnSalvarRapadura = new javax.swing.JButton();
        btnRemoverRapadura = new javax.swing.JButton();
        txtLabelEngarrafamento1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRapadura = new javax.swing.JTable();
        btnAtualizarRapadura = new javax.swing.JButton();
        btnExcluirRapadura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(111, 148, 148));

        lblLoteMelado.setText("Lote:");

        txtLoteMelado.setText("0001");

        lblPesoTotalMelado.setText("Peso Total (g)");

        txtPesoTotalMelado.setEditable(false);
        txtPesoTotalMelado.setText("0");

        lblQtdCaldoMelado.setText("Quantidade de Caldo (L):");

        lblDtProdMelado.setText("Data de Produção:");

        ftxtDtProdMelado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));

        lblRendimentoMelado.setText("Rendimento");

        txtRendimentoMelado.setEditable(false);

        txtQtdMelado.setEditable(false);
        txtQtdMelado.setText("0");

        lblQtdMelado.setText("Quantidade de Melados:");

        lblAddMelado.setText("Adição de Melado");

        lblPesoMelado.setText("Peso (g):");

        btnAddMelado.setText("Adicionar");

        btnSalvarMelado.setText("Salvar Lote");
        btnSalvarMelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMeladoActionPerformed(evt);
            }
        });

        btnMeladoVoltar.setText("Voltar");
        btnMeladoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeladoVoltarActionPerformed(evt);
            }
        });

        btnRemoverMelado.setText("Remover");

        txtLabelEngarrafamento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtLabelEngarrafamento.setText("Produção Melado");

        tblMelado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lote", "Data de Produção", "Qtd Caldo", "Qtd Melado", "Peso Total", "Rendimento", "Validade"
            }
        ));
        jScrollPane2.setViewportView(tblMelado);

        btnAtualizarMelado.setText("Atualizar");

        btnExcluirMelado.setText("Excluir");
        btnExcluirMelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMeladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMeladoLayout = new javax.swing.GroupLayout(painelMelado);
        painelMelado.setLayout(painelMeladoLayout);
        painelMeladoLayout.setHorizontalGroup(
            painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMeladoLayout.createSequentialGroup()
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMeladoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMeladoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnExcluirMelado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizarMelado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMeladoVoltar))
                            .addComponent(jSeparator2)))
                    .addGroup(painelMeladoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMeladoLayout.createSequentialGroup()
                                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtdCaldoMelado)
                                    .addComponent(lblLoteMelado)
                                    .addComponent(txtLabelEngarrafamento)
                                    .addComponent(lblDtProdMelado)
                                    .addComponent(lblQtdMelado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(painelMeladoLayout.createSequentialGroup()
                                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddMelado)
                                    .addComponent(lblPesoMelado))
                                .addGap(126, 126, 126)))
                        .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPesoMelado, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtQtdMelado)
                                .addComponent(ftxtDtProdMelado)
                                .addComponent(txtLoteMelado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(txtQtdCaldoMelado, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(44, 44, 44)
                        .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPesoTotalMelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesoTotalMelado)
                            .addComponent(lblRendimentoMelado)
                            .addComponent(txtRendimentoMelado)
                            .addComponent(btnAddMelado))
                        .addGap(18, 18, 18)
                        .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvarMelado)
                            .addComponent(btnRemoverMelado))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(painelMeladoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        painelMeladoLayout.setVerticalGroup(
            painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMeladoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtLabelEngarrafamento)
                .addGap(18, 18, 18)
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoteMelado)
                    .addComponent(txtLoteMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesoTotalMelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQtdCaldoMelado)
                        .addComponent(txtQtdCaldoMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPesoTotalMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtProdMelado)
                    .addComponent(ftxtDtProdMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRendimentoMelado))
                .addGap(4, 4, 4)
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdMelado)
                    .addComponent(txtQtdMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRendimentoMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMeladoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblAddMelado)
                        .addGap(9, 9, 9)
                        .addComponent(lblPesoMelado))
                    .addGroup(painelMeladoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesoMelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddMelado)
                            .addComponent(btnRemoverMelado))))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarMelado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(painelMeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMeladoVoltar)
                    .addComponent(btnAtualizarMelado)
                    .addComponent(btnExcluirMelado))
                .addContainerGap())
        );

        Abas.addTab("Melado", painelMelado);

        btnRapaduraVoltar.setText("Voltar");
        btnRapaduraVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRapaduraVoltarActionPerformed(evt);
            }
        });

        lblAddRapadura.setText("Adição de Rapadura");

        btnAddRapadura.setText("Adicionar");

        lblPesoRapadura.setText("Peso (g):");

        lblLoteRapadura.setText("Lote:");

        txtLoteRapadura.setText("0001");

        lblQtdCaldoRapadura.setText("Quantidade de Caldo (L):");

        lblDtProdRapadura.setText("Data de Produção:");

        ftxtDtProdRapadura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));

        lblQtdRapadura.setText("Quantidade de Rapaduras:");

        txtQtdRapadura.setEditable(false);
        txtQtdRapadura.setText("0");

        lblPesoTotalRapadura.setText("Peso Total (g)");

        txtPesoTotalRapadura.setEditable(false);
        txtPesoTotalRapadura.setText("0");

        lblRendimentoRapadura.setText("Rendimento");

        txtRendimentoRapadura.setEditable(false);

        btnSalvarRapadura.setText("Salvar Lote");
        btnSalvarRapadura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarRapaduraActionPerformed(evt);
            }
        });

        btnRemoverRapadura.setText("Remover");

        txtLabelEngarrafamento1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtLabelEngarrafamento1.setText("Produção Rapadura");

        tblRapadura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lote", "Data de Produção", "Qtd Caldo", "Qtd Rapadura", "Peso Total", "Rendimento", "Validade"
            }
        ));
        jScrollPane1.setViewportView(tblRapadura);

        btnAtualizarRapadura.setText("Atualizar");

        btnExcluirRapadura.setText("Excluir");
        btnExcluirRapadura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRapaduraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRapaduraLayout = new javax.swing.GroupLayout(painelRapadura);
        painelRapadura.setLayout(painelRapaduraLayout);
        painelRapaduraLayout.setHorizontalGroup(
            painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRapaduraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRapaduraLayout.createSequentialGroup()
                        .addComponent(lblAddRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(painelRapaduraLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnAddRapadura))
                    .addGroup(painelRapaduraLayout.createSequentialGroup()
                        .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelRapaduraLayout.createSequentialGroup()
                                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtdCaldoRapadura)
                                    .addComponent(lblLoteRapadura)
                                    .addComponent(lblDtProdRapadura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ftxtDtProdRapadura)
                                    .addComponent(txtLoteRapadura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txtQtdCaldoRapadura, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(txtLabelEngarrafamento1)
                            .addGroup(painelRapaduraLayout.createSequentialGroup()
                                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtdRapadura)
                                    .addComponent(lblPesoRapadura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPesoRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQtdRapadura))))
                        .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelRapaduraLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPesoTotalRapadura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPesoTotalRapadura)
                                    .addComponent(lblRendimentoRapadura)
                                    .addComponent(txtRendimentoRapadura)))
                            .addGroup(painelRapaduraLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnRemoverRapadura)))))
                .addGap(310, 310, 310))
            .addGroup(painelRapaduraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalvarRapadura)
                    .addComponent(jSeparator1)
                    .addGroup(painelRapaduraLayout.createSequentialGroup()
                        .addComponent(btnExcluirRapadura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizarRapadura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRapaduraVoltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRapaduraLayout.setVerticalGroup(
            painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRapaduraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtLabelEngarrafamento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoteRapadura)
                    .addComponent(txtLoteRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesoTotalRapadura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQtdCaldoRapadura)
                        .addComponent(txtQtdCaldoRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPesoTotalRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtProdRapadura)
                    .addComponent(ftxtDtProdRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRendimentoRapadura))
                .addGap(4, 4, 4)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdRapadura)
                    .addComponent(txtQtdRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRendimentoRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(lblAddRapadura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesoRapadura)
                    .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddRapadura)
                        .addComponent(txtPesoRapadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRemoverRapadura)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnSalvarRapadura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(painelRapaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRapaduraVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarRapadura)
                    .addComponent(btnExcluirRapadura))
                .addContainerGap())
        );

        Abas.addTab("Rapadura", painelRapadura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Abas, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Abas, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeladoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeladoVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnMeladoVoltarActionPerformed

    private void btnRapaduraVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRapaduraVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRapaduraVoltarActionPerformed

    private void AtualizarTabelas() {
        RapaduraDAO rDAO = new RapaduraDAO();
        MeladoDAO mDAO = new MeladoDAO();
        List<ProducaoRapadura> r = new ArrayList<ProducaoRapadura>();
        List<ProducaoMelado> m = new ArrayList<ProducaoMelado>();
        DefaultTableModel modeloR = (DefaultTableModel) tblRapadura.getModel();
        DefaultTableModel modeloM = (DefaultTableModel) tblMelado.getModel();
        modeloR.setNumRows(0);
        modeloM.setNumRows(0);
        r = rDAO.ListarRapaduras();
        m = mDAO.ListarMelado();
        r.forEach(i -> {
            modeloR.addRow(new Object[]{
                i.getLote(), i.getDtProducao(), i.getQtdCaldo(), i.getQtdRapaduras(), i.getPesoTotal(), i.getRendimento(), i.getValidade()
            });
        });
        m.forEach(i -> {
            modeloM.addRow(new Object[]{
                i.getLote(), i.getDtProducao(), i.getQtdCaldo(), i.getQtdMelado(), i.getPesoTotal(), i.getRendimento(), i.getValidade()
            });
        });
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        RapaduraDAO rDAO = new RapaduraDAO();
        MeladoDAO mDAO = new MeladoDAO();
        AtualizarTabelas();
        Integer i = rDAO.ultimoLote();
        i++;
        txtLoteRapadura.setText(i.toString());
        i = mDAO.ultimoLote();
        i++;
        txtLoteMelado.setText(i.toString());
    }//GEN-LAST:event_formWindowActivated

    private void btnSalvarMeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMeladoActionPerformed
        // TODO add your handling code here:
        ProducaoMelado p = new ProducaoMelado();
        MeladoDAO mDAO = new MeladoDAO();
        p.setLote(Integer.parseInt(txtLoteMelado.getText()));
        Date dtProducao = null;
        
        try {
            dtProducao = new SimpleDateFormat("dd/MM/yyyy").parse(ftxtDtProdMelado.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ProducaoCachacaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setDtProducao(dtProducao);
        p.setPesoTotal(Double.parseDouble(txtPesoTotalMelado.getText()));
        p.setQtdCaldo(Integer.parseInt(txtQtdCaldoMelado.getText()));
        p.setQtdMelado(Integer.parseInt(txtQtdMelado.getText()));
        p.setRendimento(Double.parseDouble(txtRendimentoMelado.getText()));
        p.calcValidade();
        
        mDAO.CriarMelado(p);
        
    }//GEN-LAST:event_btnSalvarMeladoActionPerformed

    private void btnSalvarRapaduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarRapaduraActionPerformed
        // TODO add your handling code here:
        ProducaoRapadura p = new ProducaoRapadura();
        RapaduraDAO rDAO = new RapaduraDAO();
        p.setLote(Integer.parseInt(txtLoteMelado.getText()));
        Date dtProducao = null;
        try {
            dtProducao = new SimpleDateFormat("dd/MM/yyyy").parse(ftxtDtProdRapadura.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ProducaoCachacaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setDtProducao(dtProducao);
        p.setPesoTotal(Double.parseDouble(txtPesoTotalRapadura.getText()));
        p.setQtdCaldo(Integer.parseInt(txtQtdCaldoRapadura.getText()));
        p.setQtdRapaduras(Integer.parseInt(txtQtdRapadura.getText()));
        p.setRendimento(Double.parseDouble(txtRendimentoRapadura.getText()));
        p.calcValidade();
        
        rDAO.CriarRapadura(p);
    }//GEN-LAST:event_btnSalvarRapaduraActionPerformed

    private void btnExcluirRapaduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRapaduraActionPerformed
        // TODO add your handling code here:
        RapaduraDAO rDAO = new RapaduraDAO();
        Integer lote = (Integer) tblRapadura.getValueAt(tblRapadura.getSelectedRow(), 0);
        rDAO.excluirLote(lote);
    }//GEN-LAST:event_btnExcluirRapaduraActionPerformed

    private void btnExcluirMeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMeladoActionPerformed
        // TODO add your handling code here:
        MeladoDAO mDAO = new MeladoDAO();
        Integer lote = (Integer) tblMelado.getValueAt(tblMelado.getSelectedRow(), 0);
        mDAO.excluirLote(lote);
    }//GEN-LAST:event_btnExcluirMeladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProducaoRapaduraMeladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProducaoRapaduraMeladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProducaoRapaduraMeladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProducaoRapaduraMeladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProducaoRapaduraMeladoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Abas;
    private javax.swing.JButton btnAddMelado;
    private javax.swing.JButton btnAddRapadura;
    private javax.swing.JButton btnAtualizarMelado;
    private javax.swing.JButton btnAtualizarRapadura;
    private javax.swing.JButton btnExcluirMelado;
    private javax.swing.JButton btnExcluirRapadura;
    private javax.swing.JButton btnMeladoVoltar;
    private javax.swing.JButton btnRapaduraVoltar;
    private javax.swing.JButton btnRemoverMelado;
    private javax.swing.JButton btnRemoverRapadura;
    private javax.swing.JButton btnSalvarMelado;
    private javax.swing.JButton btnSalvarRapadura;
    private javax.swing.JFormattedTextField ftxtDtProdMelado;
    private javax.swing.JFormattedTextField ftxtDtProdRapadura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAddMelado;
    private javax.swing.JLabel lblAddRapadura;
    private javax.swing.JLabel lblDtProdMelado;
    private javax.swing.JLabel lblDtProdRapadura;
    private javax.swing.JLabel lblLoteMelado;
    private javax.swing.JLabel lblLoteRapadura;
    private javax.swing.JLabel lblPesoMelado;
    private javax.swing.JLabel lblPesoRapadura;
    private javax.swing.JLabel lblPesoTotalMelado;
    private javax.swing.JLabel lblPesoTotalRapadura;
    private javax.swing.JLabel lblQtdCaldoMelado;
    private javax.swing.JLabel lblQtdCaldoRapadura;
    private javax.swing.JLabel lblQtdMelado;
    private javax.swing.JLabel lblQtdRapadura;
    private javax.swing.JLabel lblRendimentoMelado;
    private javax.swing.JLabel lblRendimentoRapadura;
    private javax.swing.JPanel painelMelado;
    private javax.swing.JPanel painelRapadura;
    private javax.swing.JTable tblMelado;
    private javax.swing.JTable tblRapadura;
    private javax.swing.JLabel txtLabelEngarrafamento;
    private javax.swing.JLabel txtLabelEngarrafamento1;
    private javax.swing.JTextField txtLoteMelado;
    private javax.swing.JTextField txtLoteRapadura;
    private javax.swing.JTextField txtPesoMelado;
    private javax.swing.JTextField txtPesoRapadura;
    private javax.swing.JTextField txtPesoTotalMelado;
    private javax.swing.JTextField txtPesoTotalRapadura;
    private javax.swing.JTextField txtQtdCaldoMelado;
    private javax.swing.JTextField txtQtdCaldoRapadura;
    private javax.swing.JTextField txtQtdMelado;
    private javax.swing.JTextField txtQtdRapadura;
    private javax.swing.JTextField txtRendimentoMelado;
    private javax.swing.JTextField txtRendimentoRapadura;
    // End of variables declaration//GEN-END:variables
}
