/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.itextpdf.kernel.events.PdfDocumentEvent;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Model.Bean.Footer;
import Model.Bean.Header;
import Model.Bean.ProducaoCachaca;
import Model.DAO.CachacaDAO;
import Model.DAO.RelatorioDAO;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author delri
 */
public class RelatoriosView extends javax.swing.JFrame {

    /**
     * Creates new form RelatoriosNeo
     */
    public RelatoriosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelDados = new javax.swing.JPanel();
        lblRendimento28d = new javax.swing.JLabel();
        lblRendimentoGeral = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnVoltar = new javax.swing.JButton();
        lblCachaca28 = new javax.swing.JLabel();
        lblRapadura28 = new javax.swing.JLabel();
        lblMelado28 = new javax.swing.JLabel();
        lblCachacaGeral = new javax.swing.JLabel();
        lblRapaduraGeral = new javax.swing.JLabel();
        lblMeladoGeral = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtCachaca28 = new javax.swing.JTextField();
        txtRapadura28 = new javax.swing.JTextField();
        txtMelado28 = new javax.swing.JTextField();
        txtCachacaGeral = new javax.swing.JTextField();
        txtRapaduraGeral = new javax.swing.JTextField();
        txtMeladoGeral = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMediaLitros28 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSomaLitros28 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMediaLitrosGeral = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSomaLitrosGeral = new javax.swing.JTextField();
        painelRelatorio = new javax.swing.JPanel();
        cbxVenda = new javax.swing.JCheckBox();
        cbxProducao = new javax.swing.JCheckBox();
        cbxLote = new javax.swing.JCheckBox();
        lblDtInicio = new javax.swing.JLabel();
        txtDtInicio = new javax.swing.JTextField();
        lblDtFinal = new javax.swing.JLabel();
        txtDtFinal = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        btnVoltarGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRendimento28d.setText("Rendimento dos últimos 28 dias:");

        lblRendimentoGeral.setText("Rendimento geral:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblCachaca28.setText("Cachaça:");

        lblRapadura28.setText("Rapadura:");

        lblMelado28.setText("Melado:");

        lblCachacaGeral.setText("Cachaça:");

        lblRapaduraGeral.setText("Rapadura:");

        lblMeladoGeral.setText("Melado:");

        jLabel1.setText("Media de produção de Cachaça em Litros dos Ultimos 28 dias:");

        jLabel2.setText("Somatorio de produção em Litros dos ultimos 28 dias:");

        jLabel3.setText("Media de produção de Cachaça em Litro Geral:");

        jLabel4.setText("Somatorio de produção em Litros Geral:");

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblRendimento28d)
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCachaca28)
                                            .addComponent(lblRapadura28)
                                            .addComponent(lblMelado28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMelado28, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(txtRapadura28)
                                            .addComponent(txtCachaca28))))
                                .addGap(96, 96, 96)
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMediaLitros28, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSomaLitros28, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRendimentoGeral)
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCachacaGeral)
                                            .addComponent(lblRapaduraGeral)
                                            .addComponent(lblMeladoGeral))
                                        .addGap(31, 31, 31)
                                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCachacaGeral)
                                            .addComponent(txtRapaduraGeral)
                                            .addComponent(txtMeladoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                                .addGap(101, 101, 101)
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtMediaLitrosGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSomaLitrosGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 270, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRendimento28d)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCachaca28)
                    .addComponent(txtCachaca28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMediaLitros28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRapadura28)
                    .addComponent(txtRapadura28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblMelado28))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMelado28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSomaLitros28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRendimentoGeral)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCachacaGeral)
                    .addComponent(txtCachacaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMediaLitrosGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRapaduraGeral)
                    .addComponent(txtRapaduraGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeladoGeral)
                    .addComponent(txtMeladoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSomaLitrosGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Relatório", painelDados);

        cbxVenda.setText("Vendas");
        cbxVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVendaActionPerformed(evt);
            }
        });

        cbxProducao.setText("Produção");
        cbxProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProducaoActionPerformed(evt);
            }
        });

        cbxLote.setText("Lotes");

        lblDtInicio.setText("Data de Início:");

        lblDtFinal.setText("Data Final:");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnVoltarGerar.setText("Voltar");
        btnVoltarGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRelatorioLayout = new javax.swing.GroupLayout(painelRelatorio);
        painelRelatorio.setLayout(painelRelatorioLayout);
        painelRelatorioLayout.setHorizontalGroup(
            painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxVenda)
                    .addComponent(cbxProducao)
                    .addComponent(cbxLote)
                    .addGroup(painelRelatorioLayout.createSequentialGroup()
                        .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDtInicio)
                            .addComponent(txtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDtFinal)
                            .addComponent(txtDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(582, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRelatorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarGerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerar)
                .addContainerGap())
        );
        painelRelatorioLayout.setVerticalGroup(
            painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProducao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxLote)
                .addGap(18, 18, 18)
                .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtInicio)
                    .addComponent(lblDtFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(btnVoltarGerar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gerar Relatório", painelRelatorio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbxVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVendaActionPerformed

    private void cbxProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProducaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProducaoActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        j.showSaveDialog(this);
        path = j.getSelectedFile().getPath();

        try {
            //gerendo documento pdf
            PdfWriter writer = new PdfWriter(path + "/RelatorioRendimento.pdf");
            PdfDocument pdf = new PdfDocument(writer);
            pdf.setTagged();
            pdf.setDefaultPageSize(PageSize.A4);
            Document doc = new Document(pdf);
            doc.setMargins(93, 36, 55, 36);

            //Criando cabeçalho
            Header header = new Header("Listagem de Rendimento por Lote");
            Footer footer = new Footer();

            pdf.addEventHandler(PdfDocumentEvent.START_PAGE, header);
            pdf.addEventHandler(PdfDocumentEvent.END_PAGE, footer);

            ///Criando a tabela
            Table tbl = new Table(3).useAllAvailableWidth();
            tbl.addCell("Lote");
            tbl.addCell("Data");
            tbl.addCell("Rendimento");

            //chamar método do DAO que retorna resultset
            ResultSet rs = new CachacaDAO().selecionarTabela();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            try {
                while (rs.next()) {
                    tbl.addCell(rs.getString("lote"));
                    tbl.addCell(formato.format(rs.getDate("dtAlambicagem")));
                    tbl.addCell(rs.getDouble("rendimento") + "");
                }
            } catch (SQLException ex) {
                Logger.getLogger(RelatoriosView.class.getName()).log(Level.SEVERE, null, ex);
            }
            //  for (int i = 0; i < cbxProducao.getRowCount(); i++) {
            // tbl.addCell(cbxProducao.getValueAt(i, 0).toString());
            // tbl.addCell(cbxProducao.getValueAt(i, 1).toString());
            //  }
            doc.add(tbl);
            footer.writeTotal(pdf);
            doc.close();

            //Abrir PDF
            File f = new File(path + "/Rendimento.pdf");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao deletar: " + ex);
        }

    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnVoltarGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarGerarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarGerarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        RelatorioDAO rDAO = new RelatorioDAO();
        ProducaoCachaca pCachaca = new ProducaoCachaca();
        pCachaca = rDAO.buscarDadosCachaca28();
        txtCachaca28.setText(pCachaca.getRendimento().toString());
        pCachaca = rDAO.buscarDadosCachacaGeral();
        txtCachacaGeral.setText(pCachaca.getRendimento().toString());
        txtMelado28.setText(rDAO.BuscarDadosMelado28().toString());
        txtMeladoGeral.setText(rDAO.BuscarDadosMeladoGeral().toString());
        txtRapadura28.setText(rDAO.BuscarDadosRapadura28().toString());
        txtRapaduraGeral.setText(rDAO.BuscarDadosRapaduraGeral().toString());
        txtSomaLitros28.setText(rDAO.SomatorioLitros28().toString());
        txtSomaLitrosGeral.setText(rDAO.SomatorioLitrosGeral().toString());
        txtMediaLitros28.setText(rDAO.MediaLitros28().toString());
        txtMediaLitrosGeral.setText(rDAO.MediaLitrosGeral().toString());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatoriosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatoriosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatoriosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatoriosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatoriosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltarGerar;
    private javax.swing.JCheckBox cbxLote;
    private javax.swing.JCheckBox cbxProducao;
    private javax.swing.JCheckBox cbxVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCachaca28;
    private javax.swing.JLabel lblCachacaGeral;
    private javax.swing.JLabel lblDtFinal;
    private javax.swing.JLabel lblDtInicio;
    private javax.swing.JLabel lblMelado28;
    private javax.swing.JLabel lblMeladoGeral;
    private javax.swing.JLabel lblRapadura28;
    private javax.swing.JLabel lblRapaduraGeral;
    private javax.swing.JLabel lblRendimento28d;
    private javax.swing.JLabel lblRendimentoGeral;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelRelatorio;
    private javax.swing.JTextField txtCachaca28;
    private javax.swing.JTextField txtCachacaGeral;
    private javax.swing.JTextField txtDtFinal;
    private javax.swing.JTextField txtDtInicio;
    private javax.swing.JTextField txtMediaLitros28;
    private javax.swing.JTextField txtMediaLitrosGeral;
    private javax.swing.JTextField txtMelado28;
    private javax.swing.JTextField txtMeladoGeral;
    private javax.swing.JTextField txtRapadura28;
    private javax.swing.JTextField txtRapaduraGeral;
    private javax.swing.JTextField txtSomaLitros28;
    private javax.swing.JTextField txtSomaLitrosGeral;
    // End of variables declaration//GEN-END:variables
}
